version: '3.9'
services:
  gateway:
    image: gateway
    build:
      context: ./services/gateway
      dockerfile: dev.Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    env_file:
      - ./services/gateway/.env
    volumes:
      - ./services/gateway/:/usr/src/app
    restart: "no"